### ISSUE TITLE
fullscreen should hide any system bars

### ISSUE THREAD

**Issue by xfnw** [JLErvin/berry#118]

**Comment by JLErvin** [comment]
I'm not totally convinced that this is necessary behavior. The freedesktop EWMH specification states that:
> _NET_WM_STATE_FULLSCREEN indicates that the window should fill the entire screen and have no window decorations. Additionally the Window Manager is responsible for restoring the original geometry after a switch from fullscreen back to normal window. For example, a presentation program would use this hint.

`berry` should be compliant with these rules (although I will note that full screen behavior is configurable). If a window takes up the entire active screen then is there any reason to hide system bars? I'm curious what the use case is for this - I'm under the impression that `berry` manages windows and nothing else. Specifically, `berry` does not manage system bars or docks since those aren't windows. 

If you disagree or have a description of your use case I'm happy to hear it and discuss some solutions.

**Comment by xfnw** [comment]
ah, makes sense
