### ISSUE TITLE
How to get workspace dimensions?

### ISSUE THREAD

**Issue by kalekundert** [JLErvin/berry#159]
I'm trying to implement hotkeys that will move and resize windows based on the dimensions of the current workspace, e.g. fill the rightmost half of the workspace, fille the middle third of the workspace, etc.  But I'm stuck because I can't figure out what the dimensions of a window's workspace are.

I looked at all the properties provided by `xprop` and `xprop -root`, but none seem to have this information.  `xrandr` does give the dimensions for each monitor, but I don't know of any way to know which monitor goes with which workspace.

Is there a way to get the workspace dimensions for the current window?  I feel like I'm missing something obvious.  If not, would you be open to adding this information to `BERRY_WINDOW_STATUS`?

**Comment by JLErvin** [comment]
I believe you can get about 75% of the way there with the current functionality. As you pointed out, the bit that is missing is that `berry` doesn't currently expose the workspace -> monitor mapping in any way publicly.

I think a good option would be to add an additional `monitor` property onto `BERRY_WINDOW_STATUS` so that we're aware of what monitor each window is rendered on. Using that information, something like `xrandr` could give us the display sizes that you're looking for.

Although, since this is a specific feature request, I wouldn't be opposed to tracking something like `mon_w` and `mon_h` (monitor-width, monitor-height) on `BERRY_WINDOW_STATUS`. I assume that enough people use these properties to move windows around that these might be useful.
