### ISSUE TITLE
[bug] configure script does not escape properly the options to config.sed (+ other problems)

### ISSUE THREAD

**Issue by AndersonTorres** [JLErvin/berry#162]
Hello! I am Anderson, from the Nixpkgs team, and specifically the maintainer of berry package.

While upgrading the version, I have found some annoying bugs the first time (full logs at https://termbin.com/uhzt):

> sed: file config.sed line 16: unknown option to `s'
> sed: file config.sed line 16: unknown option to `s'

I hacked the configure script in order to not remove `config.sed` after `die`-ing. Here is it:

> s/@prefix@/\/nix\/store\/2w4911dbpjlw2ka22q4nixpx9gx2drwa-berry-0.1.9/g
> s/@prefix@/\/nix\/store\/2w4911dbpjlw2ka22q4nixpx9gx2drwa-berry-0.1.9/g
> s/@bindir@/$\{prefix}\/bin/g
> s/@datadir@/$\{prefix}\/share/g
> s/@mandir@/$\{datadir}\/man/g
> s/@man1dir@/$\{mandir}\/man1/g
> s/@TMPDIR@/\/build/g
> s/@builddir@/$\{TMPDIR\}\/make/g
> s/@CC@/gcc/g
> s/@CC@/gcc/g
> s/@CC@/gcc/g
> s/@CC@/gcc/g
> s/@CC@/clang/g
> s/@CC@/cc/g
> s/@INSTALL@/install/g
> s/@pkg_cflags@/-I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include/
> s/@pkg_libs@/-lX11 -lXinerama -lfontconfig -lfreetype -lXft/
> s/@pkg_ldflags@//
> s/@pkg_name@/berry/g
> s/@pkg_version@/0x017/g
> s/@pkg_verstr@/0.1.7/g
> s/@pkg_string@/berry 0.1.7/g
> s/@pkg_uname@/BERRY/g
> s/@pkg_bugreport@/Joshua L Ervin <joshue@uw.edu>/g
> s/@pkg_major@/0/g
> s/@pkg_minor@/1/g
> s/@pkg_build@/7/g
> 

I have noticed that this line

> s/@pkg_cflags@/-I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include/

is a bit problematic for sed, because it does not escape the `/`.

------------------------------------------------------------------------

On the other hand, there is another subtle problem: the script relies on the existence of `which`.
And `which` is neither a POSIX standardized tool, nor a portable one.

The sure-fire way is to use the standard shell builtin `command`.
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html

Indeed I opened a PR fro this issue: https://github.com/JLErvin/berry/pull/163

---------------------------------------

The third problem: `pkg_verstr="0.1.7"` is outdated.

https://github.com/JLErvin/berry/blob/538de113a3646fc525ed62f7c5be638f2260d288/configure#L7

**Comment by msharov** [comment]
`configure` escapes cflags on line 178:
https://github.com/JLErvin/berry/blob/538de113a3646fc525ed62f7c5be638f2260d288/configure#L178

Non-escaping default cflags was a problem addressed in your other issue #153 and was fixed by commit f6ff9e18f0f04970ef101bc2be12d550b082d713. Please check that you have pulled that commit in.

`pkg_verstr` is supposed to be updated in configure (line 7) for each release. This is easy to forget to do, since configure will ask git for the current version when building in an active repository, but there is no way to do that when building from a distribution tarball, which does not include that information. And after the release is tagged there is no way to fix it until the next release. Annoying, but I don't see how to improve this situation. Release version must be written in the code somewhere...

As for your dislike of `which`, there is no alternative that I know of. Nor do I know of any OS that does not provide it. Doesn't yours? The `command` builtin does not do the same thing; it executes the given command rather than output its location.

**Comment by AndersonTorres** [comment]
Installing `which` is not a serious problem to me. It can be easily provided as a build input.
